defaultEntryPoints = ["http","https"]

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[docker]
endpoint="unix:///var/run/docker.sock"
domain="#DOMAIN#"
watch=true

[acme]
email = "#EMAIL_ADDRESS#"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false